"""Initial migration

Revision ID: 2024b0168a92
Revises: 9be41ca214d4
Create Date: 2026-05-07 20:03:22.868382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2024b0168a92'
down_revision = '9be41ca214d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
