"""Initial migration

Revision ID: 971f4a4dde68
Revises: d10d0a70d66a
Create Date: 2026-05-08 15:56:15.886332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971f4a4dde68'
down_revision = 'd10d0a70d66a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
