"""Initial migration

Revision ID: bc4e6df4854d
Revises: 2024b0168a92
Create Date: 2026-05-08 10:45:08.611951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4e6df4854d'
down_revision = '2024b0168a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
