"""Initial migration

Revision ID: d10d0a70d66a
Revises: bc4e6df4854d
Create Date: 2026-05-08 11:06:20.237212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd10d0a70d66a'
down_revision = 'bc4e6df4854d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('browser', sa.String(length=100), nullable=True))
    op.drop_column('device', 'brower')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('brower', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.drop_column('device', 'browser')
    # ### end Alembic commands ###
